export const locationTriggers = [
  {
    id: "union_plaza",
    label: "Union Plaza",
    shortLabel: "Union",
    x: 520,
    y: 1230,
    radius: 110,
    dialogueEventId: "union_plaza",
    collectibleId: "union_pin",
    color: 0xbe0000,
  },
  {
    id: "library_walk",
    label: "Library Walk",
    shortLabel: "Library",
    x: 1060,
    y: 980,
    radius: 110,
    dialogueEventId: "library_walk",
    collectibleId: "research_patch",
    color: 0xffb81d,
  },
  {
    id: "innovation_hub",
    label: "Innovation Hub",
    shortLabel: "Hub",
    x: 1580,
    y: 760,
    radius: 110,
    dialogueEventId: "innovation_hub",
    collectibleId: "launch_badge",
    color: 0x3abfc0,
  },
  {
    id: "health_commons",
    label: "Health Commons",
    shortLabel: "Health",
    x: 2120,
    y: 1110,
    radius: 110,
    dialogueEventId: "health_commons",
    collectibleId: "granite_pass",
    color: 0x708e99,
  },
  {
    id: "skyline_terrace",
    label: "Skyline Terrace",
    shortLabel: "Terrace",
    x: 2420,
    y: 510,
    radius: 110,
    dialogueEventId: "skyline_terrace",
    collectibleId: "city_postcard",
    color: 0x890000,
  },
];

export const locationTriggersById = Object.fromEntries(
  locationTriggers.map((trigger) => [trigger.id, trigger]),
);
