const rawPrograms = [
  ["Anthropology", "Social and Behavioral Science", "society_policy"],
  ["Art History", "Fine Arts", "design_making"],
  ["Ballet", "Fine Arts", "design_making"],
  ["Chinese", "Humanities", "humanities_culture"],
  ["Classics", "Humanities", "humanities_culture"],
  ["Construction Engineering", "Engineering", "engineering_innovation"],
  ["Criminology", "Social and Behavioral Science", "society_policy"],
  ["Dance Teaching", "Fine Arts", "design_making"],
  ["Data Science", "Engineering", "engineering_innovation"],
  ["Design", "Architecture", "design_making"],
  ["Elementary Education", "Education", "education_impact"],
  ["Environmental and Sustainability Studies", "Social and Behavioral Science", "society_policy"],
  ["Ethnic Studies", "Humanities", "society_policy"],
  ["Exercise and Sport Science Teaching", "Health", "health_care"],
  ["French Teaching", "Humanities", "humanities_culture"],
  ["Games", "Architecture", "design_making"],
  ["Geoscience", "Science", "science_research"],
  ["Graphic Design", "Fine Arts", "design_making"],
  ["History", "Humanities", "humanities_culture"],
  ["Information Systems", "Business", "business_leadership"],
  ["International Studies", "Humanities", "humanities_culture"],
  ["Latin American Studies", "Humanities", "humanities_culture"],
  ["Linguistics", "Humanities", "humanities_culture"],
  ["Operations and Supply Chain", "Business", "business_leadership"],
  ["Parks, Recreation and Tourism", "Health", "health_care"],
  ["Philosophy of Science", "Humanities", "humanities_culture"],
  ["Physics", "Science", "science_research"],
  ["Pre Law", "Undergraduate Studies", "campus_exploration"],
  ["Pre Medicine", "Undergraduate Studies", "campus_exploration"],
  ["Law", "Law", "society_policy"],
  ["Sociology", "Social and Behavioral Science", "society_policy"],
  ["Special Education", "Education", "education_impact"],
  ["Theatre", "Fine Arts", "design_making"],
  ["Undeclared", "Undergraduate Studies", "campus_exploration"],
  ["Writing and Rhetoric Studies", "Humanities", "humanities_culture"],
  ["Pre Pharmacy", "Undergraduate Studies", "campus_exploration"],
  ["Pre Dentistry", "Undergraduate Studies", "campus_exploration"],
  ["Political Science", "Social and Behavioral Science", "society_policy"],
  ["Physics Teaching", "Science", "science_research"],
  ["Philosophy", "Humanities", "humanities_culture"],
  ["Peace and Conflict Studies", "Humanities", "humanities_culture"],
  ["Nursing", "Nursing", "health_care"],
  ["Music", "Fine Arts", "design_making"],
  ["Modern Dance", "Fine Arts", "design_making"],
  ["Mining Engineering", "Science", "science_research"],
  ["Middle East Studies", "Humanities", "humanities_culture"],
  ["Metallurgical Engineering", "Science", "science_research"],
  ["Medical Laboratory Science", "Medicine", "health_care"],
  ["Mechanical Engineering", "Engineering", "engineering_innovation"],
  ["Mathematics Teaching", "Science", "science_research"],
  ["Mathematics", "Science", "science_research"],
  ["Materials Science and Engineering", "Engineering", "engineering_innovation"],
  ["Marketing", "Business", "business_leadership"],
  ["Management", "Business", "business_leadership"],
  ["Kinesiology Teaching", "Health", "health_care"],
  ["Kinesiology", "Health", "health_care"],
  ["Japanese", "Humanities", "humanities_culture"],
  ["Human Development and Family Studies", "Social and Behavioral Science", "society_policy"],
  ["History Teaching", "Humanities", "humanities_culture"],
  ["Health, Society and Policy", "Social and Behavioral Science", "society_policy"],
  ["Health Promotion and Education Teaching", "Health", "health_care"],
  ["Health Promotion and Education", "Health", "health_care"],
  ["Health and Kinesiology", "Health", "health_care"],
  ["German Teaching", "Humanities", "humanities_culture"],
  ["German", "Humanities", "humanities_culture"],
  ["Geological Engineering", "Science", "science_research"],
  ["Geography", "Social and Behavioral Science", "society_policy"],
  ["Geographic Information Science", "Social and Behavioral Science", "society_policy"],
  ["Gender Studies", "Humanities", "society_policy"],
  ["French", "Humanities", "humanities_culture"],
  ["Finance", "Business", "business_leadership"],
  ["Film and Media Arts", "Fine Arts", "design_making"],
  ["Family, Community and Human Development", "Social and Behavioral Science", "society_policy"],
  ["Exercise and Sport Science", "Health", "health_care"],
  ["Entrepreneurship", "Business", "business_leadership"],
  ["English Teaching", "Humanities", "humanities_culture"],
  ["English", "Humanities", "humanities_culture"],
  ["Electrical Engineering", "Engineering", "engineering_innovation"],
  ["Educational Psychology", "Education", "education_impact"],
  ["Economics", "Social and Behavioral Science", "society_policy"],
  ["Consumer and Community Studies", "Social and Behavioral Science", "society_policy"],
  ["Computer Science", "Engineering", "engineering_innovation"],
  ["Computer Engineering", "Engineering", "engineering_innovation"],
  ["Comparative Literary and Cultural Studies", "Humanities", "humanities_culture"],
  ["Communication", "Humanities", "humanities_culture"],
  ["Civil Engineering", "Engineering", "engineering_innovation"],
  ["Chemistry Teaching", "Science", "science_research"],
  ["Chemistry", "Science", "science_research"],
  ["Chemical Engineering", "Engineering", "engineering_innovation"],
  ["Business Administration", "Business", "business_leadership"],
  ["Biomedical Engineering", "Engineering", "engineering_innovation"],
  ["Biology Teaching", "Science", "science_research"],
  ["Biology Composite Teaching", "Science", "science_research"],
  ["Biology", "Science", "science_research"],
  ["Atmospheric Sciences", "Science", "science_research"],
  ["Athletic Training", "Health", "health_care"],
  ["Asian Studies", "Humanities", "humanities_culture"],
  ["Art Teaching", "Fine Arts", "design_making"],
  ["Art Composite Teaching", "Fine Arts", "design_making"],
  ["Art", "Fine Arts", "design_making"],
  ["Architectural Studies", "Architecture", "design_making"],
  ["Applied Mathematics", "Science", "science_research"],
  ["Accounting", "Business", "business_leadership"],
  ["Urban Ecology", "Architecture", "design_making"],
  ["Speech and Hearing Science", "Health", "health_care"],
  ["Spanish Teaching", "Humanities", "humanities_culture"],
  ["Spanish", "Humanities", "humanities_culture"],
  ["Social Work", "Social Work", "human_support"],
  ["Russian Teaching", "Humanities", "humanities_culture"],
  ["Russian", "Humanities", "humanities_culture"],
  ["Religious Studies", "Humanities", "humanities_culture"],
  ["Recreational Therapy", "Health", "health_care"],
  ["Quantitative Analysis of Markets and Organizations", "Business", "business_leadership"],
  ["Psychology", "Social and Behavioral Science", "society_policy"],
  ["Theatre Teaching", "Fine Arts", "design_making"],
];

function slugify(value) {
  return value
    .toLowerCase()
    .replaceAll("&", " and ")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export const colleges = Array.from(
  new Map(
    rawPrograms.map(([, collegeLabel]) => [
      slugify(collegeLabel),
      { id: slugify(collegeLabel), label: collegeLabel },
    ]),
  ).values(),
).sort((left, right) => left.label.localeCompare(right.label));

export const programs = rawPrograms
  .map(([label, collegeLabel, programFamilyId]) => ({
    id: slugify(label),
    label,
    collegeId: slugify(collegeLabel),
    collegeLabel,
    degreeLabel: "Major",
    catalogUrl: "https://catalog.utah.edu/programs",
    programFamilyId,
  }))
  .sort((left, right) => left.collegeLabel.localeCompare(right.collegeLabel) || left.label.localeCompare(right.label));

export const collegesById = Object.fromEntries(colleges.map((college) => [college.id, college]));
export const programsById = Object.fromEntries(programs.map((program) => [program.id, program]));
export const programsByCollegeId = Object.fromEntries(
  colleges.map((college) => [
    college.id,
    programs.filter((program) => program.collegeId === college.id),
  ]),
);
