export const REQUIRED_STOPS = 5;

const COLORS = {
  red: 0xbe0000,
  sunrise: 0xffb81d,
  lake: 0x3abfc0,
  granite: 0x708e99,
  ember: 0x890000,
};

export const tourStops = [
  {
    id: "block_u",
    label: "Block U",
    shortLabel: "Block U",
    x: 1055,
    y: 936,
    radius: 120,
    color: COLORS.red,
    imageAsset: "blockU",
    body:
      "At Block U, the tour opens with the same idea captured in the source material: your path is not chosen for you, it is built by you. This is where curiosity turns into direction.",
  },
  {
    id: "uac",
    label: "U Asia Campus",
    shortLabel: "UAC",
    x: 2870,
    y: 1853,
    radius: 115,
    color: COLORS.lake,
    imageAsset: "uac",
    body:
      "The U's global footprint expands what college can look like. This stop reflects the tour's emphasis on global experiences and the idea that your Utah story can connect to a much wider world.",
  },
  {
    id: "umfa",
    label: "UMFA",
    shortLabel: "UMFA",
    x: 1869,
    y: 1860,
    radius: 115,
    color: COLORS.sunrise,
    imageAsset: "umfa",
    body:
      "UMFA signals how the university connects learning with art, culture, and public-facing creativity. It is a reminder that expression and perspective are part of campus life too.",
  },
  {
    id: "kahlert_village",
    label: "Kahlert Village",
    shortLabel: "Kahlert",
    x: 1357,
    y: 766,
    radius: 120,
    color: COLORS.granite,
    imageAsset: "kahlertVillage",
    body:
      "The housing tour object makes this clear: first-year students are guaranteed on-campus housing, and living here helps people build community and network early.",
  },
  {
    id: "honors_housing",
    label: "Honors Housing",
    shortLabel: "Honors",
    x: 1589,
    y: 645,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "honorsHousing",
    body:
      "The Honors College offers an interdisciplinary academic experience for high-achieving students. It emphasizes critical thinking, research, and intellectual exploration across disciplines. Students engage in small, discussion-based courses and collaborative projects. The program culminates in a capstone thesis or creative project. Honors students graduate with enhanced academic depth and a strong foundation for graduate study or professional careers.",
  },
  {
    id: "safety",
    label: "Public Safety Building",
    shortLabel: "Safety",
    x: 1901,
    y: 1481,
    radius: 120,
    color: COLORS.ember,
    imageAsset: "safety",
    body:
      "The tour's safety script emphasizes 24/7 public safety services and security escorts. The point is simple: students should feel supported here day or night.",
  },
  {
    id: "student_services",
    label: "Student Services",
    shortLabel: "Services",
    x: 1275,
    y: 1182,
    radius: 120,
    color: COLORS.sunrise,
    imageAsset: "studentServices",
    body:
      "Student Services pulls in the financial-aid tour copy: merit-based and need-based scholarships, plus millions awarded annually, all framed around making higher education more affordable.",
  },
  {
    id: "gardner_commons",
    label: "Gardner Commons",
    shortLabel: "Gardner",
    x: 1525,
    y: 1339,
    radius: 120,
    color: COLORS.red,
    imageAsset: "gardnerCommons",
    body:
      "The majors tour begins here with a counselor asking what you are interested in. It frames the university as a place with room for science, business, education, engineering, social work, law, honors, and more.",
  },
  {
    id: "undergraduate_studies",
    label: "Undergraduate Studies",
    shortLabel: "UG Studies",
    x: 1444,
    y: 940,
    radius: 115,
    color: COLORS.red,
    imageAsset: "undergraduateStudies",
    body:
      "This stop carries the same exploratory spirit as the major-selection sequence: a lot of paths open here, and the real task is figuring out which kind of learning feels most like you.",
  },
  {
    id: "architecture",
    label: "Architecture Building",
    shortLabel: "Architecture",
    x: 2553,
    y: 1020,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "architecture",
    body:
      "The College of Architecture + Planning focuses on shaping the built environment through design, innovation, and community impact. Students explore fields like architecture, urban planning, game design, and multidisciplinary design, blending creativity with real-world problem solving. The college emphasizes sustainability, equity, and the relationship between people and spaces. Hands-on studios, research, and community projects prepare students to address modern environmental and urban challenges. Graduates leave ready to design spaces and systems that improve how we live, work, and connect.",
  },
  {
    id: "science",
    label: "Science",
    shortLabel: "Science",
    x: 2368,
    y: 757,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "science",
    body:
      "The College of Science provides a foundation in disciplines like biology, chemistry, physics, and mathematics. Students engage in research, lab work, and problem-solving across scientific fields. The college emphasizes discovery, innovation, and analytical thinking. Interdisciplinary opportunities allow students to explore emerging areas of science. Graduates are prepared for careers in research, industry, healthcare, and beyond.",
  },
  {
    id: "health",
    label: "Health",
    shortLabel: "Health",
    x: 2190,
    y: 593,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "health",
    body:
      "The College of Health focuses on improving quality of life through health sciences, wellness, and prevention. Programs span areas like kinesiology, nutrition, and health promotion. Students gain practical experience through labs, internships, and community engagement. The college emphasizes holistic health and evidence-based practices. Graduates are prepared to promote healthier communities and support public well-being.",
  },
  {
    id: "arts_building",
    label: "Arts Building",
    shortLabel: "Arts",
    x: 1229,
    y: 1588,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "artsBuilding",
    body:
      "The College of Fine Arts nurtures creativity across visual art, music, theatre, dance, and film. Students develop their artistic voice while gaining technical skills and professional experience. The college emphasizes performance, exhibition, and collaboration. Opportunities to engage with the broader arts community enhance learning. Graduates are prepared to contribute to the cultural landscape as artists, performers, and creative leaders.",
  },
  {
    id: "engineering",
    label: "Engineering",
    shortLabel: "Engineering",
    x: 832,
    y: 895,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "engineering",
    body:
      "The College of Engineering offers cutting-edge programs across disciplines like biomedical, civil, electrical, and computer engineering. Students engage in hands-on projects, research, and industry partnerships that tackle real-world challenges. Innovation and problem-solving are central to the curriculum. The college supports interdisciplinary collaboration and entrepreneurship. Graduates are prepared to design technologies and systems that drive progress across industries.",
  },
  {
    id: "social_work",
    label: "Social Work",
    shortLabel: "Social Work",
    x: 1736,
    y: 955,
    radius: 110,
    color: COLORS.red,
    imageAsset: "socialWork",
    body:
      "The College of Social Work prepares students to support individuals, families, and communities. Programs focus on advocacy, clinical practice, and social justice. Students gain hands-on experience through field placements. The college emphasizes equity, inclusion, and community impact. Graduates are equipped to create positive change and improve lives through professional social work practice.",
  },
  {
    id: "csbs",
    label: "CSBS",
    shortLabel: "CSBS",
    x: 1787,
    y: 871,
    radius: 110,
    color: COLORS.red,
    imageAsset: "csbs",
    body:
      "The College of Social and Behavioral Science examines human behavior and societal systems. Programs include psychology, economics, political science, and sociology. Students develop analytical and research skills to understand complex social issues. The college emphasizes real-world application and policy impact. Graduates are prepared to address societal challenges and inform decision-making.",
  },
  {
    id: "education",
    label: "Education",
    shortLabel: "Education",
    x: 1614,
    y: 760,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "education",
    body:
      "The College of Education prepares students to become effective educators, leaders, and advocates in diverse learning environments. Programs focus on teaching, educational leadership, counseling, and policy. Students gain hands-on classroom experience while studying evidence-based practices. The college emphasizes equity, inclusion, and lifelong learning. Graduates are ready to shape educational systems and support student success at every level.",
  },
  {
    id: "community_service",
    label: "Community Service",
    shortLabel: "Service",
    x: 1936,
    y: 685,
    radius: 110,
    color: COLORS.red,
    imageAsset: "communityService",
    body:
      "Service is one of the original interest tags, and the activities object reinforces the idea that campus life here is about finding your people and making your effort count beyond yourself.",
  },
  {
    id: "library",
    label: "Library",
    shortLabel: "Library",
    x: 1629,
    y: 1173,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "library",
    body:
      "The library stop stands for the quieter side of the same major exploration: research support, study space, and the infrastructure that helps students turn interest into progress.",
  },
  {
    id: "business",
    label: "Eccles Business Building",
    shortLabel: "Business",
    x: 1228,
    y: 1373,
    radius: 120,
    color: COLORS.sunrise,
    imageAsset: "business",
    body:
      "The David Eccles School of Business prepares students to lead in a rapidly evolving global economy. Programs span entrepreneurship, finance, marketing, operations, and more, with a strong emphasis on innovation and real-world application. Students gain hands-on experience through internships, consulting projects, and startup opportunities. The school is known for fostering an entrepreneurial mindset and strong industry connections. Graduates are equipped to drive growth, solve complex business challenges, and create meaningful impact in organizations of all sizes.",
  },
  {
    id: "night_life",
    label: "Night Life",
    shortLabel: "Night Life",
    x: 325,
    y: 1442,
    radius: 110,
    color: COLORS.ember,
    imageAsset: "downtown",
    body:
      "This stop adds the after-hours side of the city-campus experience: concerts, late nights, and the kind of social energy that makes Salt Lake feel bigger than the classroom.",
  },
  {
    id: "food",
    label: "Food",
    shortLabel: "Food",
    x: 2400,
    y: 1853,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "food",
    body:
      "The activities object calls out everything from late-night bites to global cuisine. This stop is about daily campus life feeling varied, social, and easy to enjoy.",
  },
  {
    id: "student_life_center",
    label: "Student Life Center",
    shortLabel: "Life Center",
    x: 2064,
    y: 880,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "studentLifeCenter",
    body:
      "With 600+ clubs and a strong fitness culture in the activities object, this stop captures the side of campus where routines, recreation, and belonging all come together.",
  },
  {
    id: "jobs",
    label: "Jobs",
    shortLabel: "Jobs",
    x: 2836,
    y: 758,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "jobs",
    body:
      "This stop extends the source material's leadership and city-access themes into internships, campus jobs, and the practical opportunities that make college feel connected to life after graduation.",
  },
  {
    id: "humanities",
    label: "Humanities",
    shortLabel: "Humanities",
    x: 1310,
    y: 1079,
    radius: 110,
    color: COLORS.red,
    imageAsset: "humanities",
    body:
      "The College of Humanities explores human culture, language, history, and ideas. Programs include disciplines like literature, philosophy, languages, and communication. Students develop critical thinking, writing, and analytical skills. The college emphasizes global perspectives and cultural understanding. Graduates are prepared for careers that require strong communication, creativity, and insight into the human experience.",
  },
  {
    id: "nursing",
    label: "Nursing",
    shortLabel: "Nursing",
    x: 2412,
    y: 668,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "nursing",
    body:
      "The College of Nursing prepares students for compassionate, evidence-based patient care. Programs emphasize clinical practice, research, and leadership in healthcare settings. Students gain hands-on experience in diverse medical environments. The college promotes innovation in healthcare delivery and patient outcomes. Graduates are ready to lead in nursing practice and improve health systems.",
  },
  {
    id: "law",
    label: "Law Building",
    shortLabel: "Law",
    x: 1120,
    y: 1538,
    radius: 120,
    color: COLORS.red,
    imageAsset: "law",
    body:
      "The S.J. Quinney College of Law prepares students for leadership in the legal profession. The curriculum combines rigorous legal training with hands-on experience through clinics and externships. Students explore areas like environmental law, business law, and public interest law. The college emphasizes ethics, public service, and advocacy. Graduates are equipped to navigate complex legal systems and drive meaningful change.",
  },
  {
    id: "lds_institute",
    label: "LDS Institute",
    shortLabel: "Institute",
    x: 715,
    y: 761,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "ldsInstitute",
    body:
      "This stop adds another community-oriented space to the map, reflecting the broader theme that students here build networks and find places that support both identity and belonging.",
  },
  {
    id: "rice_eccles",
    label: "Rice-Eccles Stadium",
    shortLabel: "Stadium",
    x: 2714,
    y: 1396,
    radius: 135,
    color: COLORS.granite,
    imageAsset: "riceEccles",
    body:
      "The activities source calls out school spirit and sports directly. Rice-Eccles turns that into a stop about tradition, crowd energy, and being part of something bigger.",
  },
  {
    id: "transportation",
    label: "UTA TRAX Stop",
    shortLabel: "Transit",
    x: 2238,
    y: 1528,
    radius: 130,
    color: COLORS.lake,
    imageAsset: "transportation",
    body:
      "The transportation source is direct: your student ID is your ticket to ride, and buses and TRAX run all day. This stop is about access, independence, and a connected campus.",
  },
  {
    id: "downtown",
    label: "Downtown Salt Lake City",
    shortLabel: "Downtown",
    x: 512,
    y: 435,
    radius: 120,
    color: COLORS.lake,
    imageAsset: "downtown",
    body:
      "The activity prompts frame Salt Lake City as part of the experience: city life, food, music venues, and opportunity without losing proximity to the outdoors.",
  },
  {
    id: "red_butte",
    label: "Red Butte Garden",
    shortLabel: "Red Butte",
    x: 325,
    y: 1229,
    radius: 135,
    color: COLORS.ember,
    imageAsset: "redButte",
    body:
      "Red Butte reflects the tour's outdoors category and the idea that campus life here stays connected to the landscape, trails, and room to reset.",
  },
  {
    id: "outdoors",
    label: "Outdoors",
    shortLabel: "Outdoors",
    x: 316,
    y: 974,
    radius: 120,
    color: COLORS.lake,
    imageAsset: "outdoors",
    body:
      "The original activities object makes the outdoors one of the defining parts of the U experience, from nearby camping to quick access to mountain space.",
  },
  {
    id: "ski_snowboard",
    label: "Ski and Snowboard",
    shortLabel: "Ski",
    x: 1393,
    y: 1867,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "skiSnowboard",
    body:
      "One of the clearest facts in the activities file is that there are 11 ski resorts less than an hour away. This stop turns that into a campus-life advantage you can actually feel.",
  },
];

export const tourStopsById = Object.fromEntries(tourStops.map((stop) => [stop.id, stop]));
