export const REQUIRED_STOPS = 5;

const COLORS = {
  red: 0xbe0000,
  sunrise: 0xffb81d,
  lake: 0x3abfc0,
  granite: 0x708e99,
  ember: 0x890000,
};

function createCollectible(id, label) {
  return {
    id: `${id}-stamp`,
    label: `${label} Stamp`,
    unlockCopy: `A tour stamp from ${label}.`,
  };
}

export const tourStops = [
  {
    id: "block_u",
    label: "Block U",
    shortLabel: "Block U",
    x: 1055,
    y: 936,
    radius: 120,
    color: COLORS.red,
    imageAsset: "blockU",
    collectible: createCollectible("block_u", "Block U"),
    body:
      "At Block U, the tour opens with the same idea captured in the source material: your path is not chosen for you, it is built by you. This is where curiosity turns into direction.",
  },
  {
    id: "uac",
    label: "U Asia Campus",
    shortLabel: "UAC",
    x: 2870,
    y: 1853,
    radius: 115,
    color: COLORS.lake,
    imageAsset: "uac",
    collectible: createCollectible("uac", "U Asia Campus"),
    body:
      "The U's global footprint expands what college can look like. This stop reflects the tour's emphasis on global experiences and the idea that your Utah story can connect to a much wider world.",
  },
  {
    id: "umfa",
    label: "UMFA",
    shortLabel: "UMFA",
    x: 1869,
    y: 1860,
    radius: 115,
    color: COLORS.sunrise,
    imageAsset: "umfa",
    collectible: createCollectible("umfa", "UMFA"),
    body:
      "UMFA signals how the university connects learning with art, culture, and public-facing creativity. It is a reminder that expression and perspective are part of campus life too.",
  },
  {
    id: "kahlert_village",
    label: "Kahlert Village",
    shortLabel: "Kahlert",
    x: 1357,
    y: 766,
    radius: 120,
    color: COLORS.granite,
    imageAsset: "kahlertVillage",
    collectible: createCollectible("kahlert_village", "Kahlert Village"),
    body:
      "The housing tour object makes this clear: first-year students are guaranteed on-campus housing, and living here helps people build community and network early.",
  },
  {
    id: "honors_housing",
    label: "Honors Housing",
    shortLabel: "Honors",
    x: 1589,
    y: 645,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "honorsHousing",
    collectible: createCollectible("honors_housing", "Honors Housing"),
    body:
      "This stop extends the housing story toward a more close-knit academic community, where students balance residential life with a stronger sense of intellectual connection.",
  },
  {
    id: "safety",
    label: "Public Safety Building",
    shortLabel: "Safety",
    x: 1901,
    y: 1481,
    radius: 120,
    color: COLORS.ember,
    imageAsset: "safety",
    collectible: createCollectible("safety", "Public Safety"),
    body:
      "The tour's safety script emphasizes 24/7 public safety services and security escorts. The point is simple: students should feel supported here day or night.",
  },
  {
    id: "student_services",
    label: "Student Services",
    shortLabel: "Services",
    x: 1275,
    y: 1182,
    radius: 120,
    color: COLORS.sunrise,
    imageAsset: "studentServices",
    collectible: createCollectible("student_services", "Student Services"),
    body:
      "Student Services pulls in the financial-aid tour copy: merit-based and need-based scholarships, plus millions awarded annually, all framed around making higher education more affordable.",
  },
  {
    id: "gardner_commons",
    label: "Gardner Commons",
    shortLabel: "Gardner",
    x: 1525,
    y: 1339,
    radius: 120,
    color: COLORS.red,
    imageAsset: "gardnerCommons",
    collectible: createCollectible("gardner_commons", "Gardner Commons"),
    body:
      "The majors tour begins here with a counselor asking what you are interested in. It frames the university as a place with room for science, business, education, engineering, social work, law, honors, and more.",
  },
  {
    id: "undergraduate_studies",
    label: "Undergraduate Studies",
    shortLabel: "UG Studies",
    x: 1444,
    y: 940,
    radius: 115,
    color: COLORS.red,
    imageAsset: "undergraduateStudies",
    collectible: createCollectible("undergraduate_studies", "Undergraduate Studies"),
    body:
      "This stop carries the same exploratory spirit as the major-selection sequence: a lot of paths open here, and the real task is figuring out which kind of learning feels most like you.",
  },
  {
    id: "architecture",
    label: "Architecture Building",
    shortLabel: "Architecture",
    x: 2553,
    y: 1020,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "architecture",
    collectible: createCollectible("architecture", "Architecture"),
    body:
      "Architecture appears in the major categories as part of a more design-driven path, where visual thinking, building, and systems all work together.",
  },
  {
    id: "science",
    label: "Science",
    shortLabel: "Science",
    x: 2368,
    y: 757,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "science",
    collectible: createCollectible("science", "Science"),
    body:
      "Science and research are called out directly in the majors source. This stop represents the part of campus built around discovery, inquiry, and asking better questions.",
  },
  {
    id: "health",
    label: "Health",
    shortLabel: "Health",
    x: 2190,
    y: 593,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "health",
    collectible: createCollectible("health", "Health"),
    body:
      "Healthcare is one of the interest tags in the original tour objects, and this stop pushes that people-first direction into a health-focused campus setting.",
  },
  {
    id: "arts_building",
    label: "Arts Building",
    shortLabel: "Arts",
    x: 1229,
    y: 1588,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "artsBuilding",
    collectible: createCollectible("arts_building", "Arts Building"),
    body:
      "The majors list explicitly includes arts and creativity, and this stop turns that into a real place on the map where making, performing, and producing ideas can take shape.",
  },
  {
    id: "engineering",
    label: "Engineering",
    shortLabel: "Engineering",
    x: 832,
    y: 895,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "engineering",
    collectible: createCollectible("engineering", "Engineering"),
    body:
      "Engineering and technology are core major categories in the tour object, representing the builder side of campus where curiosity turns into tools, prototypes, and systems.",
  },
  {
    id: "social_work",
    label: "Social Work",
    shortLabel: "Social Work",
    x: 1736,
    y: 955,
    radius: 110,
    color: COLORS.red,
    imageAsset: "socialWork",
    collectible: createCollectible("social_work", "Social Work"),
    body:
      "Social Work is named directly in the tour's major categories. It points toward work rooted in support, advocacy, and helping communities move forward.",
  },
  {
    id: "csbs",
    label: "CSBS",
    shortLabel: "CSBS",
    x: 1787,
    y: 871,
    radius: 110,
    color: COLORS.red,
    imageAsset: "csbs",
    collectible: createCollectible("csbs", "CSBS"),
    body:
      "The College of Social and Behavioral Science sits at the intersection of people, policy, research, and systems. It is a strong match for students interested in how communities actually work.",
  },
  {
    id: "education",
    label: "Education",
    shortLabel: "Education",
    x: 1614,
    y: 760,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "education",
    collectible: createCollectible("education", "Education"),
    body:
      "Education appears in the majors source as part of a social-impact pathway. This stop represents learning that is designed to help other people grow.",
  },
  {
    id: "community_service",
    label: "Community Service",
    shortLabel: "Service",
    x: 1936,
    y: 685,
    radius: 110,
    color: COLORS.red,
    imageAsset: "communityService",
    collectible: createCollectible("community_service", "Community Service"),
    body:
      "Service is one of the original interest tags, and the activities object reinforces the idea that campus life here is about finding your people and making your effort count beyond yourself.",
  },
  {
    id: "library",
    label: "Library",
    shortLabel: "Library",
    x: 1629,
    y: 1173,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "library",
    collectible: createCollectible("library", "Library"),
    body:
      "The library stop stands for the quieter side of the same major exploration: research support, study space, and the infrastructure that helps students turn interest into progress.",
  },
  {
    id: "business",
    label: "Eccles Business Building",
    shortLabel: "Business",
    x: 1228,
    y: 1373,
    radius: 120,
    color: COLORS.sunrise,
    imageAsset: "business",
    collectible: createCollectible("business", "Business"),
    body:
      "Business and leadership are both central to the source objects, which frame the U as a place to build initiative, entrepreneurship, and momentum that moves people forward.",
  },
  {
    id: "night_life",
    label: "Night Life",
    shortLabel: "Night Life",
    x: 325,
    y: 1442,
    radius: 110,
    color: COLORS.ember,
    imageAsset: "downtown",
    collectible: createCollectible("night_life", "Night Life"),
    body:
      "This stop adds the after-hours side of the city-campus experience: concerts, late nights, and the kind of social energy that makes Salt Lake feel bigger than the classroom.",
  },
  {
    id: "food",
    label: "Food",
    shortLabel: "Food",
    x: 2400,
    y: 1853,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "food",
    collectible: createCollectible("food", "Food"),
    body:
      "The activities object calls out everything from late-night bites to global cuisine. This stop is about daily campus life feeling varied, social, and easy to enjoy.",
  },
  {
    id: "student_life_center",
    label: "Student Life Center",
    shortLabel: "Life Center",
    x: 2064,
    y: 880,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "studentLifeCenter",
    collectible: createCollectible("student_life_center", "Student Life Center"),
    body:
      "With 600+ clubs and a strong fitness culture in the activities object, this stop captures the side of campus where routines, recreation, and belonging all come together.",
  },
  {
    id: "jobs",
    label: "Jobs",
    shortLabel: "Jobs",
    x: 2836,
    y: 758,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "jobs",
    collectible: createCollectible("jobs", "Jobs"),
    body:
      "This stop extends the source material's leadership and city-access themes into internships, campus jobs, and the practical opportunities that make college feel connected to life after graduation.",
  },
  {
    id: "humanities",
    label: "Humanities",
    shortLabel: "Humanities",
    x: 1310,
    y: 1079,
    radius: 110,
    color: COLORS.red,
    imageAsset: "humanities",
    collectible: createCollectible("humanities", "Humanities"),
    body:
      "Humanities is explicitly named in the major categories and points toward language, ideas, culture, ethics, and the kinds of questions that shape how people understand the world.",
  },
  {
    id: "nursing",
    label: "Nursing",
    shortLabel: "Nursing",
    x: 2412,
    y: 668,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "nursing",
    collectible: createCollectible("nursing", "Nursing"),
    body:
      "Nursing is another direct major callout in the source file. It represents a clear care-centered route where skill, urgency, and human connection meet.",
  },
  {
    id: "law",
    label: "Law Building",
    shortLabel: "Law",
    x: 1120,
    y: 1538,
    radius: 120,
    color: COLORS.red,
    imageAsset: "law",
    collectible: createCollectible("law", "Law"),
    body:
      "Law appears in the tour's major categories as one of the more direct leadership-oriented routes, where advocacy, systems, and public impact all matter.",
  },
  {
    id: "lds_institute",
    label: "LDS Institute",
    shortLabel: "Institute",
    x: 715,
    y: 761,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "ldsInstitute",
    collectible: createCollectible("lds_institute", "LDS Institute"),
    body:
      "This stop adds another community-oriented space to the map, reflecting the broader theme that students here build networks and find places that support both identity and belonging.",
  },
  {
    id: "rice_eccles",
    label: "Rice-Eccles Stadium",
    shortLabel: "Stadium",
    x: 2714,
    y: 1396,
    radius: 135,
    color: COLORS.granite,
    imageAsset: "riceEccles",
    collectible: createCollectible("rice_eccles", "Rice-Eccles Stadium"),
    body:
      "The activities source calls out school spirit and sports directly. Rice-Eccles turns that into a stop about tradition, crowd energy, and being part of something bigger.",
  },
  {
    id: "transportation",
    label: "UTA TRAX Stop",
    shortLabel: "Transit",
    x: 2238,
    y: 1528,
    radius: 130,
    color: COLORS.lake,
    imageAsset: "transportation",
    collectible: createCollectible("transportation", "Transportation"),
    body:
      "The transportation source is direct: your student ID is your ticket to ride, and buses and TRAX run all day. This stop is about access, independence, and a connected campus.",
  },
  {
    id: "downtown",
    label: "Downtown Salt Lake City",
    shortLabel: "Downtown",
    x: 512,
    y: 435,
    radius: 120,
    color: COLORS.lake,
    imageAsset: "downtown",
    collectible: createCollectible("downtown", "Downtown"),
    body:
      "The activity prompts frame Salt Lake City as part of the experience: city life, food, music venues, and opportunity without losing proximity to the outdoors.",
  },
  {
    id: "red_butte",
    label: "Red Butte Garden",
    shortLabel: "Red Butte",
    x: 325,
    y: 1229,
    radius: 135,
    color: COLORS.ember,
    imageAsset: "redButte",
    collectible: createCollectible("red_butte", "Red Butte Garden"),
    body:
      "Red Butte reflects the tour's outdoors category and the idea that campus life here stays connected to the landscape, trails, and room to reset.",
  },
  {
    id: "outdoors",
    label: "Outdoors",
    shortLabel: "Outdoors",
    x: 316,
    y: 974,
    radius: 120,
    color: COLORS.lake,
    imageAsset: "outdoors",
    collectible: createCollectible("outdoors", "Outdoors"),
    body:
      "The original activities object makes the outdoors one of the defining parts of the U experience, from nearby camping to quick access to mountain space.",
  },
  {
    id: "ski_snowboard",
    label: "Ski and Snowboard",
    shortLabel: "Ski",
    x: 1393,
    y: 1867,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "skiSnowboard",
    collectible: createCollectible("ski_snowboard", "Ski and Snowboard"),
    body:
      "One of the clearest facts in the activities file is that there are 11 ski resorts less than an hour away. This stop turns that into a campus-life advantage you can actually feel.",
  },
];

export const tourStopsById = Object.fromEntries(tourStops.map((stop) => [stop.id, stop]));
