export const REQUIRED_STOPS = 5;

const COLORS = {
  red: 0xbe0000,
  sunrise: 0xffb81d,
  lake: 0x3abfc0,
  granite: 0x708e99,
  ember: 0x890000,
};

export const tourStops = [
  {
    id: "block_u",
    label: "Block U",
    shortLabel: "Block U",
    x: 1055,
    y: 936,
    radius: 120,
    color: COLORS.red,
    imageAsset: "blockU",
    body:
      "Block U sets the tone for the whole visit: this is a place to build your own path. From your first day on campus, the U encourages you to explore what matters to you and move toward it with purpose.",
  },
  {
    id: "uac",
    label: "U Asia Campus",
    shortLabel: "UAC",
    x: 2870,
    y: 1853,
    radius: 115,
    color: COLORS.lake,
    imageAsset: "uac",
    body:
      "The U Asia Campus shows how far a Utah education can reach. It adds a global dimension to your experience, connecting campus life here with opportunities to learn, grow, and build community across borders.",
  },
  {
    id: "umfa",
    label: "UMFA",
    shortLabel: "UMFA",
    x: 1869,
    y: 1860,
    radius: 115,
    color: COLORS.sunrise,
    imageAsset: "umfa",
    body:
      "At UMFA, creativity becomes part of everyday campus life. It is one of the places that reminds you the U values perspective, expression, and the kind of learning that reaches beyond the classroom.",
  },
  {
    id: "kahlert_village",
    label: "Kahlert Village",
    shortLabel: "Kahlert",
    x: 1357,
    y: 766,
    radius: 120,
    color: COLORS.granite,
    imageAsset: "kahlertVillage",
    body:
      "Kahlert Village reflects one of the clearest student-life advantages at the U: first-year students are guaranteed on-campus housing. Living here helps you find your people early, build community, and start college with support close by.",
  },
  {
    id: "honors_housing",
    label: "Honors Housing",
    shortLabel: "Honors",
    x: 1589,
    y: 645,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "honorsHousing",
    body:
      "Honors Housing connects to the Honors College experience: an interdisciplinary path built around critical thinking, research, and close-knit academic community. It is a place where ambitious students can live among peers who want to push their ideas further.",
  },
  {
    id: "safety",
    label: "Public Safety Building",
    shortLabel: "Safety",
    x: 1901,
    y: 1481,
    radius: 120,
    color: COLORS.ember,
    imageAsset: "safety",
    body:
      "The Public Safety Building represents a simple promise: your safety matters here, day or night. With 24/7 public safety services, campus-wide safety features, and security escorts, the U works to make campus feel supportive and secure.",
  },
  {
    id: "student_services",
    label: "Student Services",
    shortLabel: "Services",
    x: 1275,
    y: 1182,
    radius: 120,
    color: COLORS.sunrise,
    imageAsset: "studentServices",
    body:
      "Student Services is where affordability becomes real support. The U offers merit-based and need-based scholarships, awards millions in financial aid each year, and works to make a Utah education more accessible for in-state and out-of-state students alike.",
  },
  {
    id: "gardner_commons",
    label: "Gardner Commons",
    shortLabel: "Gardner",
    x: 1525,
    y: 1339,
    radius: 120,
    color: COLORS.red,
    imageAsset: "gardnerCommons",
    body:
      "Gardner Commons captures the starting point for academic exploration at the U. It is where big questions about your future turn into real options across disciplines, with guidance that helps you connect your interests to a path forward.",
  },
  {
    id: "undergraduate_studies",
    label: "Undergraduate Studies",
    shortLabel: "UG Studies",
    x: 1444,
    y: 940,
    radius: 115,
    color: COLORS.red,
    imageAsset: "undergraduateStudies",
    body:
      "Undergraduate Studies reflects the freedom to explore before locking in a direction. With so many paths available, this part of the journey is about discovering the kind of learning, challenge, and community that fits you best.",
  },
  {
    id: "architecture",
    label: "Architecture Building",
    shortLabel: "Architecture",
    x: 2553,
    y: 1020,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "architecture",
    body:
      "The College of Architecture + Planning is where creativity meets impact. Students study architecture, planning, game design, and multidisciplinary design while using hands-on studios and community projects to shape spaces and systems that improve how people live and connect.",
  },
  {
    id: "science",
    label: "Science",
    shortLabel: "Science",
    x: 2368,
    y: 757,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "science",
    body:
      "The College of Science builds a strong foundation in fields like biology, chemistry, physics, and mathematics. Through research, lab work, and interdisciplinary problem-solving, students learn how to turn curiosity into discovery and real-world impact.",
  },
  {
    id: "health",
    label: "Health",
    shortLabel: "Health",
    x: 2190,
    y: 593,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "health",
    body:
      "The College of Health focuses on helping people live better through wellness, prevention, and health science. Students gain practical experience in areas like kinesiology, nutrition, and health promotion while preparing to strengthen healthier communities.",
  },
  {
    id: "arts_building",
    label: "Arts Building",
    shortLabel: "Arts",
    x: 1229,
    y: 1588,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "artsBuilding",
    body:
      "The College of Fine Arts gives students room to create, perform, and collaborate across visual art, music, theatre, dance, and film. It is a place to develop your artistic voice while gaining the experience and discipline to share it with the world.",
  },
  {
    id: "engineering",
    label: "Engineering",
    shortLabel: "Engineering",
    x: 832,
    y: 895,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "engineering",
    body:
      "The College of Engineering is built around hands-on problem-solving. Across disciplines like biomedical, civil, electrical, and computer engineering, students work on real challenges through research, projects, and industry partnerships that prepare them to build what comes next.",
  },
  {
    id: "social_work",
    label: "Social Work",
    shortLabel: "Social Work",
    x: 1736,
    y: 955,
    radius: 110,
    color: COLORS.red,
    imageAsset: "socialWork",
    body:
      "The College of Social Work prepares students to support individuals, families, and communities through advocacy, clinical practice, and social justice. Field experience and community impact are central here, so students graduate ready to help create meaningful change.",
  },
  {
    id: "csbs",
    label: "CSBS",
    shortLabel: "CSBS",
    x: 1787,
    y: 871,
    radius: 110,
    color: COLORS.red,
    imageAsset: "csbs",
    body:
      "The College of Social and Behavioral Science helps students understand people, systems, and the forces that shape society. Through fields like psychology, economics, political science, and sociology, students build the research and analytical skills to address real social challenges.",
  },
  {
    id: "education",
    label: "Education",
    shortLabel: "Education",
    x: 1614,
    y: 760,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "education",
    body:
      "The College of Education prepares future teachers, counselors, leaders, and advocates to serve diverse learners. With hands-on experience and a strong focus on equity and evidence-based practice, students are ready to support success at every level of education.",
  },
  {
    id: "community_service",
    label: "Community Service",
    shortLabel: "Service",
    x: 1936,
    y: 685,
    radius: 110,
    color: COLORS.red,
    imageAsset: "communityService",
    body:
      "Community service at the U is about turning care into action. There are many ways to get involved, give back, and shape the community around you, making service part of how you build purpose and connection here.",
  },
  {
    id: "library",
    label: "Library",
    shortLabel: "Library",
    x: 1629,
    y: 1173,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "library",
    body:
      "The library represents the academic support behind every path at the U. It gives students the space, tools, and research help to turn questions into progress, whether they are exploring a new subject or pushing deeper into a major.",
  },
  {
    id: "business",
    label: "Eccles Business Building",
    shortLabel: "Business",
    x: 1228,
    y: 1373,
    radius: 120,
    color: COLORS.sunrise,
    imageAsset: "business",
    body:
      "The David Eccles School of Business prepares students to lead with confidence in a fast-moving economy. With strengths in entrepreneurship, finance, marketing, operations, and more, it combines classroom learning with internships, consulting, and startup experience that connect directly to career outcomes.",
  },
  {
    id: "night_life",
    label: "Night Life",
    shortLabel: "Night Life",
    x: 325,
    y: 1442,
    radius: 110,
    color: COLORS.ember,
    imageAsset: "downtown",
    body:
      "Night life gives you another side of the Salt Lake experience. Just a quick ride from campus, evenings can mean live music, late-night food, or time with friends in a city that stays active without feeling overwhelming.",
  },
  {
    id: "food",
    label: "Food",
    shortLabel: "Food",
    x: 2400,
    y: 1853,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "food",
    body:
      "Food is part of what makes daily life here feel lively and social. From late-night favorites to global cuisine, Salt Lake offers plenty of ways to try something new and make meals part of the experience.",
  },
  {
    id: "student_life_center",
    label: "Student Life Center",
    shortLabel: "Life Center",
    x: 2064,
    y: 880,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "studentLifeCenter",
    body:
      "The Student Life Center brings together two big parts of campus life: staying active and finding your community. Between top-tier fitness facilities and more than 600 student clubs, it is easy to build routines, friendships, and a sense of belonging here.",
  },
  {
    id: "jobs",
    label: "Jobs",
    shortLabel: "Jobs",
    x: 2836,
    y: 758,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "jobs",
    body:
      "Jobs around campus help students build experience while they study. Whether you are looking for on-campus work or nearby opportunities that fit your schedule, this is one more way the U connects college life with practical growth and future career momentum.",
  },
  {
    id: "humanities",
    label: "Humanities",
    shortLabel: "Humanities",
    x: 1310,
    y: 1079,
    radius: 110,
    color: COLORS.red,
    imageAsset: "humanities",
    body:
      "The College of Humanities explores culture, language, history, and ideas in ways that sharpen how students think and communicate. It is a strong fit for students who want to pair curiosity about people and meaning with writing, analysis, and global perspective.",
  },
  {
    id: "nursing",
    label: "Nursing",
    shortLabel: "Nursing",
    x: 2412,
    y: 668,
    radius: 110,
    color: COLORS.sunrise,
    imageAsset: "nursing",
    body:
      "The College of Nursing prepares students for compassionate, evidence-based care through clinical training, research, and leadership development. With experience in diverse healthcare settings, students are ready to improve patient outcomes and lead in a changing health system.",
  },
  {
    id: "law",
    label: "Law Building",
    shortLabel: "Law",
    x: 1120,
    y: 1538,
    radius: 120,
    color: COLORS.red,
    imageAsset: "law",
    body:
      "The S.J. Quinney College of Law prepares students for leadership through rigorous legal study and hands-on experience in clinics and externships. With strengths in areas like environmental, business, and public interest law, it is a place where advocacy and service carry real weight.",
  },
  {
    id: "lds_institute",
    label: "LDS Institute",
    shortLabel: "Institute",
    x: 715,
    y: 761,
    radius: 110,
    color: COLORS.granite,
    imageAsset: "ldsInstitute",
    body:
      "The LDS Institute reflects a broader truth about campus life: students need spaces where they feel grounded and connected. The U supports a community with room for faith, identity, and belonging alongside academic growth.",
  },
  {
    id: "rice_eccles",
    label: "Rice-Eccles Stadium",
    shortLabel: "Stadium",
    x: 2714,
    y: 1396,
    radius: 135,
    color: COLORS.granite,
    imageAsset: "riceEccles",
    body:
      "Rice-Eccles Stadium is where school spirit gets loud. From major football moments to the energy of the Mighty Utah Student Section, this stop captures the pride, tradition, and shared excitement that make game day feel bigger than the scoreboard.",
  },
  {
    id: "transportation",
    label: "UTA TRAX Stop",
    shortLabel: "Transit",
    x: 2238,
    y: 1528,
    radius: 130,
    color: COLORS.lake,
    imageAsset: "transportation",
    body:
      "Transportation at the U makes the city and campus easier to navigate. Your student ID is your ticket to ride, and with buses and TRAX running throughout the day, getting to class, downtown, or the mountains feels simple and flexible.",
  },
  {
    id: "downtown",
    label: "Downtown Salt Lake City",
    shortLabel: "Downtown",
    x: 512,
    y: 435,
    radius: 120,
    color: COLORS.lake,
    imageAsset: "downtown",
    body:
      "Downtown Salt Lake City adds energy and opportunity to the college experience. You get the benefits of a real city, from food and events to internships and culture, without giving up quick access to the outdoors.",
  },
  {
    id: "red_butte",
    label: "Red Butte Garden",
    shortLabel: "Red Butte",
    x: 325,
    y: 1229,
    radius: 135,
    color: COLORS.ember,
    imageAsset: "redButte",
    body:
      "Red Butte Garden shows how closely campus life is tied to the landscape around it. It is a place for concerts, views, and a quick reset, all while staying connected to the energy of the university.",
  },
  {
    id: "outdoors",
    label: "Outdoors",
    shortLabel: "Outdoors",
    x: 316,
    y: 974,
    radius: 120,
    color: COLORS.lake,
    imageAsset: "outdoors",
    body:
      "The outdoors are one of the defining parts of life at the U. With nearby camping, mountain trails, and five national parks within reach for a weekend, getting outside is not an occasional bonus here, it is part of the rhythm of living in Utah.",
  },
  {
    id: "ski_snowboard",
    label: "Ski and Snowboard",
    shortLabel: "Ski",
    x: 1393,
    y: 1867,
    radius: 110,
    color: COLORS.lake,
    imageAsset: "skiSnowboard",
    body:
      "Skiing and snowboarding are woven into the Utah experience. With 11 resorts less than an hour from campus, it is entirely possible to go from class to the slopes and make world-class snow part of your normal week.",
  },
];

export const tourStopsById = Object.fromEntries(tourStops.map((stop) => [stop.id, stop]));
